### ISSUE TITLE
WebAssembly.compile(): Argument 0 must be a buffer source

### ISSUE THREAD

**Issue by BadMachine** [donmccurdy/keyframe-resample-wasm#4]
Facing this issue with my own module. Decided to install yours to check - so its the same.
![image](https://github.com/donmccurdy/keyframe-resample-wasm/assets/50546204/bf44c772-6647-4b7b-85c5-aad6ad42b5f4)

**Comment by donmccurdy** [comment]
@BadMachine Hi! I'm happy to take a look if you could share enough information for me to reproduce the problem. I haven't seen that error before.

Full code in a simple test case is ideal, but at the minimum:

- environment: web browser? node.js version? deno version?
- installation method: npm? cdn? 
- bundler: appears to be vite – which version of vite? 

Also note there's [more than one way to import this module](https://github.com/donmccurdy/keyframe-resample-wasm#api), please share which you're using, and any other relevant details.

**Comment by BadMachine** [comment]
Hey @donmccurdy!
Vite version is "^4.3.2".
Yes, im using npm. Test app is a react application template.
Chrome browser 119.0.6045.160
Node version was 18.* at the time of tests.

In vite config I added
```
  optimizeDeps: {
    exclude: ['keyframe-resample'],
  },
```
since it solves my problem with importing .wasm file in another project (havok wasm library)

**Comment by donmccurdy** [comment]
It sounds like this is a bug or limitation in Vite or Esbuild – bundler support for WASM has always been rocky. Also note that there's a `keyframe-resample/compat` entrypoint you can use if your bundler doesn't support WASM fully. Longer discussion of the WASM issues in this article:

https://web.dev/articles/bundling-non-js-resources

I'm already offering multiple entrypoints to work around the many difficulties of packaging WASM (see below), and I'm not sure of anything more that can be done within this module, but would be interested if you find recommendations.

https://github.com/donmccurdy/keyframe-resample-wasm/blob/b4498ba3944e8385c6accfad9ec7282f119bc105/package.json#L9-L27

**Comment by fightZy** [comment]
I think this is just an API usage error. WebAssembly. compile receives a BufferSource parameter, but fetch returns a Response


![image](https://github.com/donmccurdy/keyframe-resample-wasm/assets/52490455/4084b56a-c157-44b7-821c-dae876b5165d)
<img width="718" alt="image" src="https://github.com/donmccurdy/keyframe-resample-wasm/assets/52490455/2e60a189-a52e-4f2f-bfbd-a00ddb19cdcb">

**Comment by donmccurdy** [comment]
Thanks @BadMachine and @fightZy! That does look like an issue, and might explain why the tests (which run in node.js) still passed. I think this should be fixed by https://github.com/donmccurdy/keyframe-resample-wasm/commit/9fcf2f767376003cd8bbc6746a207f06d06ed929, published in v0.0.16.
